spring:
  application:
    name: policy-management
  datasource:
    url: ${SUPABASE_DB_URL}
    username: postgres
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

supabase:
  url: ${SUPABASE_URL}
  key: ${SUPABASE_SERVICE_ROLE_KEY}
  anon-key: ${SUPABASE_ANON_KEY}
  storage:
    bucket: policies

jwt:
  secret: ${JWT_SECRET:your-secret-key-change-in-production}
  expiration: 86400000

server:
  port: 8080

logging:
  level:
    com.company.policymanagement: DEBUG
    org.springframework.security: DEBUG